### PR TITLE
fix: server tweaks

### PR DESCRIPTION
**Pull request by apopheny**
- renamed getTopicsAndSchemas.js to getAndInsertTopicsAndSchemas.js to reflect export and functionality
- changed export in same module to function rather than function call
- added .env processing for user-defined server port, SERVER_PORT
- changed default port to 3010 to avoid potential collisions
- added more descriptive error message to /pipelines GET route

### CODE REVIEW

**Comment by apopheny** [comment]
Additional fix: updated getAndInsertTopicsAndSchemas.js to use connection pool from db.js (resolved error "Error listing topics and schemas: Error: Client has already been connected. You cannot reuse a client.")

**Comment by apopheny** [comment]
Additional fix: updated server.js to use connection pool from db.js (resolved error "Error listing topics and schemas: Error: Client has already been connected. You cannot reuse a client.")

**Comment by apopheny** [comment]
Tweak: updated put pipelines route to retrieve id from request body for better integration with FE Zod

**Review by benhancock — APPROVED** [review]
Good changes. LGTM!

**Pull request merged**
